runtime: python36
entrypoint: gunicorn -b :$PORT "CAWPr:create_app()" --timeout 300
env_variables:
	GOOGLE_CLOUD_BUCKET: "gs://cawp-47548.appspot.com/"
	REMOTE_BLOB_NAME: "testGAE" 
	INSTANCE_CONNECION_NAME: "cawp-47548:us-east4:testsql"
	DATABASE_USERNAME: "postgres"
	DATABASE_PASSWORD: "Maccabi01"
	DATABASE_NAME: "postgres"
	DATABASE_HOST: "/cloudsql/$INSTANCE_CONNECTION_NAME/.s.PGSQL.5432"	
